"""Compliance and testing checklist for a batch tender report.

Built entirely from the report: every item points at a standard, a requirement
and the evidence that produced it, so nothing on the checklist is generated by
a language model or added from general practice. Items are prompts for the
officer to act on and tick off, not determinations — certification flags come
from a curated rule table, and abstained requirements need an engineer.
"""
from __future__ import annotations
import re
from typing import Any

SECTIONS = [
    ("correct", "Correct outdated references",
     "Standards the tender cites that the BIS catalogue has since revised or withdrawn."),
    ("specify", "Standards to specify",
     "The standards each requirement was matched to, with the edition and amendments to cite."),
    ("certify", "Certification to obtain",
     "Mandatory certification schemes that apply to the specified products."),
    ("test", "Testing to perform",
     "Test methods the specified standards cite, with the clause that cites them."),
    ("safety", "Safety requirements",
     "Safety standards the specified standards cite."),
    ("resolve", "Requirements needing an engineer",
     "No standard could be matched with confidence; an engineer must specify one."),
]

_SCHEME = {
    "BIS_PRODUCT_CERT": "a valid BIS Product Certification licence (ISI mark)",
    "CRS": "valid BIS Compulsory Registration (CRS)",
    "HALLMARKING": "BIS hallmarking",
}


# Some BIS catalogue titles were stored double-encoded ("â€”" for "—").
_MOJIBAKE = re.compile(r"\u00e2\u20ac|\u00c3[\u0080-\u00bf]")

# BIS files some glossaries under a testing or safety aspect. Telling a bidder to
# "test in accordance with" a vocabulary would be wrong, so they are left out.
_GLOSSARY = re.compile(r"\b(vocabulary|terminology|glossary|definitions)\b", re.I)

# An edge's type comes from the cited standard's BIS aspect, and a misread
# citation can attach an unrelated standard, so the testing section keeps only
# standards whose own title says they test something. The rest stay in the
# report's allied standards, where they are shown with their evidence.
_TESTS = re.compile(r"\b(test(s|ing)?|methods? of|determination|measurement|"
                    r"evaluation|assessment|classification)\b", re.I)


def _clean(title: str | None) -> str | None:
    if title and _MOJIBAKE.search(title):
        try:
            return title.encode("cp1252").decode("utf-8")
        except (UnicodeEncodeError, UnicodeDecodeError):
            pass
    return title


def _std(num: str | None, title: str | None) -> str:
    title = _clean(title)
    return f"{num} — {title}" if title else (num or "")


def build_checklist(report: dict[str, Any]) -> dict[str, Any]:
    items: dict[str, list[dict[str, Any]]] = {k: [] for k, _, _ in SECTIONS}

    # ---- outdated references in the tender itself
    for c in report.get("outdated_document_citations") or []:
        cited, latest = c.get("cited_as"), c.get("latest_known_edition")
        if c.get("status") == "withdrawn":
            action = f"Remove the withdrawn standard “{cited}” and specify a current alternative."
        else:
            action = f"Replace “{cited}” with {latest or 'the current edition'}."
        items["correct"].append({
            "action": action, "standard": latest or c.get("is_number"),
            "requirement_ids": [], "basis": " ".join(c.get("flags") or []),
        })

    # ---- per matched standard: specify, certify, test, safety
    specify: dict[str, dict[str, Any]] = {}
    certify: dict[tuple[str, str], dict[str, Any]] = {}
    allied: dict[tuple[str, str], dict[str, Any]] = {}

    for entry in report.get("results") or []:
        req, res = entry.get("requirement") or {}, entry.get("result") or {}
        rid = req.get("id")

        if res.get("status") == "abstained":
            near = [c.get("is_number") for c in (res.get("closest_candidates") or [])[:3]]
            basis = " ".join((res.get("reasons") or [])[:1])
            if near:
                basis += f" Closest candidates: {', '.join(n for n in near if n)}."
            items["resolve"].append({
                "action": f"Specify a standard for {rid} manually: “{req.get('text', '').strip()}”",
                "standard": None, "requirement_ids": [rid], "basis": basis.strip(),
            })
            continue

        primaries = res.get("primary_standards") or []
        for ps in primaries:
            num = ps.get("is_number")
            if not num:
                continue
            s = specify.setdefault(num, {"ps": ps, "reqs": [], "conf": []})
            s["reqs"].append(rid)
            s["conf"].append(res.get("confidence"))

            for sch in (ps.get("certification") or {}).get("schemes") or []:
                if not sch.get("mandatory"):
                    continue
                key = (num, sch.get("scheme"))
                c = certify.setdefault(key, {"sch": sch, "reqs": []})
                c["reqs"].append(rid)

        # Allied standards hang off the primaries of this result.
        by = ", ".join(p.get("is_number") for p in primaries if p.get("is_number"))
        for a in res.get("allied_standards") or []:
            kind = {"test_method": "test", "safety": "safety"}.get(a.get("edge_type"))
            title = a.get("title") or ""
            if not kind or not a.get("is_number") or _GLOSSARY.search(title):
                continue
            if kind == "test" and not _TESTS.search(title):
                continue
            key = (kind, a["is_number"])
            e = allied.setdefault(key, {"a": a, "reqs": [], "cited": []})
            e["reqs"].append(rid)
            where = f"{by} ({a['cited_at']})" if a.get("cited_at") else by
            if where and where not in e["cited"]:
                e["cited"].append(where)

    for num, s in specify.items():
        ps = s["ps"]
        cur = ps.get("currency") or {}
        notes = []
        confs = [c for c in s["conf"] if c is not None]
        if confs:
            notes.append(f"Matched at confidence {min(confs):.2f}.")
        n = cur.get("amendment_count") or 0
        if n:
            notes.append(f"{n} amendment{'s' if n != 1 else ''} issued against this edition must be read with it.")
        if cur.get("status") in ("superseded", "withdrawn"):
            notes.append(f"This edition is {cur['status']}"
                         + (f"; the newest is {cur['latest_known_edition']}." if cur.get("latest_known_edition") else "."))
        if ps.get("metadata_only"):
            notes.append("Matched on catalogue metadata only; confirm the scope against the standard's text.")
        items["specify"].append({
            "action": f"Specify {_std(num, ps.get('title'))}.",
            "standard": num, "requirement_ids": s["reqs"], "basis": " ".join(notes),
        })

    for (num, scheme), c in certify.items():
        sch = c["sch"]
        basis = [f"{sch['authority']}." if sch.get("authority") else "",
                 f"Rule match: {sch['match']}." if sch.get("match") else "",
                 "Weak match; confirm it applies." if sch.get("confidence") == "low" else "",
                 "Verify against the current notification before relying on it."]
        items["certify"].append({
            "action": f"Require {_SCHEME.get(scheme, scheme)} for products to {num}, "
                      f"and a copy of the certificate with the bid.",
            "standard": num, "requirement_ids": c["reqs"],
            "basis": " ".join(b for b in basis if b),
        })

    for (kind, num), e in allied.items():
        a = e["a"]
        verb = "Test in accordance with" if kind == "test" else "Comply with"
        basis = f"Cited by {'; '.join(e['cited'])}." if e["cited"] else ""
        if a.get("withdrawn"):
            basis += " This standard is withdrawn; confirm its replacement."
        elif a.get("in_corpus") is False:
            basis += " Outside the ingested corpus; its currency was not checked."
        items[kind].append({
            "action": f"{verb} {_std(num, a.get('title'))}.",
            "standard": num, "requirement_ids": e["reqs"], "basis": basis.strip(),
        })

    out, n = [], 0
    for key, title, about in SECTIONS:
        rows = items[key]
        for it in rows:
            n += 1
            it["id"] = f"C{n}"
            it["requirement_ids"] = list(dict.fromkeys(r for r in it["requirement_ids"] if r))
        out.append({"key": key, "title": title, "about": about, "items": rows})

    return {
        "sections": out,
        "total": n,
        "note": ("Generated from this report's matches, citations and rule table. "
                 "Certification flags are prompts to verify, not legal determinations."),
    }
